name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: true
    default: ${{ github.actor }}@localhost
name:
  description: The commiter's name 
  required: true
  default: ${{ github.actor }}